### ISSUE TITLE
Redesign Implementation

### ISSUE THREAD

**Issue by eidens** [source-data/sdash#240]
We've received the new design, now we need to implement it. Here's the roadmap for the components or views that need to be changed:

Pages:
- [x] Dashboard
- [x] #271
- [x] #258
- [x] Single panel
- [x] About
- [x] #262
- [x] User Profile
- [x] #276
- [x] #277
- [x] #282 

Components:
- [x] Navigation bar (consistent across all pages):
  - [x] Main design
  - [x] Search bar
  - [x] #261
- [x] Panel upload dropzone
- [x] #243
  - [x] Panel Detail:
    - [x] Title & authors
    - [x] Description
    - [x] Comments
    - [x] #268
    - [x] #269
    - [x] #270
  - [x] #252
  - [x] #263
- [x] #264
- [x] Footer with Call to Action, Contact, Partners
- [x] Feedback widget

This list will be updated once changes are implemented.

**Comment by HannahSonntag** [comment]
@eidens in the single panel view:
as we discussed today: 
- Do we want to keep empty boxes (eg when there is no description) No, please hide empty boxes. 
- Sources: when there is no ‘description’ or ‘category’ for a source it looks weird. Therefore:
Include the table headings (wording similar to the detail view).  
First coloumn should be the Filename/URL since it is the only mandatory item. 
- Have the keywords in the SD colours as in the detail view.

**Comment by eidens** [comment]
> @eidens in the single panel view: as we discussed today:
> 
>     * Do we want to keep empty boxes (eg when there is no description) No, please hide empty boxes.
> 
>     * Sources: when there is no ‘description’ or ‘category’ for a source it looks weird. Therefore:
>       Include the table headings (wording similar to the detail view).
>       First coloumn should be the Filename/URL since it is the only mandatory item.
> 
>     * Have the keywords in the SD colours as in the detail view.

All of that is completed. And with that, I think we're done here :)
